# Generated by Django 5.2.16 on 2026-09-18 16:42

import django.db.models.deletion
import django_jalali.db.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان سرویس')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='درصد کمیسیون آژانس')),
                ('base_fare', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کرایه پایه (تومان)')),
                ('per_km_fare', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کرایه هر کیلومتر (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سرویس شهری',
                'verbose_name_plural': 'سرویس\u200cهای شهری',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان نرخ\u200cنامه')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'سواری'), ('vanet', 'ون'), ('pickup', 'وانت'), ('nissan', 'نیسان'), ('minibus', 'مینی\u200cبوس'), ('other', 'سایر')], default='sedan', max_length=20, verbose_name='نوع خودرو')),
                ('base_fare', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کرایه پایه (تومان)')),
                ('per_km_fare', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کرایه هر کیلومتر (تومان)')),
                ('minimum_fare', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حداقل کرایه (تومان)')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='درصد کمیسیون آژانس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_rate_cards_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_cards', to='city_drivers.urbanservice', verbose_name='سرویس مرتبط')),
            ],
            options={
                'verbose_name': 'نرخ\u200cنامه',
                'verbose_name_plural': 'نرخ\u200cنامه\u200cها',
                'ordering': ('-is_active', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد رهگیری')),
                ('origin_address', models.TextField(verbose_name='آدرس مبدأ')),
                ('destination_address', models.TextField(verbose_name='آدرس مقصد')),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی مبدأ')),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی مبدأ')),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی مقصد')),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی مقصد')),
                ('passenger_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مسافر/گیرنده')),
                ('passenger_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن مسافر/گیرنده')),
                ('requested_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان نوبت درخواست')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='مسافت (کیلومتر)')),
                ('fare_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='کرایه (تومان)')),
                ('commission_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کمیسیون آژانس (تومان)')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='کمیسیون تسویه شد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('assigned', 'تخصیص یافته'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده'), ('canceled', 'لغو شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_service_requests', to='drivers.driver', verbose_name='راننده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urban_service_requests', to='customers.customer', verbose_name='مشتری')),
                ('rate_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='city_drivers.ratecard', verbose_name='نرخ\u200cنامه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_requests_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='city_drivers.urbanservice', verbose_name='نوع سرویس')),
            ],
            options={
                'verbose_name': 'درخواست سرویس شهری',
                'verbose_name_plural': 'درخواست\u200cهای سرویس شهری',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('status', models.CharField(choices=[('idle', 'بدون سرویس'), ('busy', 'در حال انجام سرویس')], default='idle', max_length=10, verbose_name='وضعیت کاری')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urban_location', to='drivers.driver', verbose_name='راننده')),
                ('current_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_locations', to='city_drivers.servicerequest', verbose_name='سرویس جاری')),
            ],
            options={
                'verbose_name': 'موقعیت راننده',
                'verbose_name_plural': 'موقعیت رانندگان',
            },
        ),
        migrations.CreateModel(
            name='CommissionDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ بدهی (تومان)')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='پرداخت شده (تومان)')),
                ('is_settled', models.BooleanField(default=False, verbose_name='تسویه شده')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تسویه')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urban_commission_debts', to='drivers.driver', verbose_name='راننده')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_debts', to='city_drivers.servicerequest', verbose_name='سرویس مرتبط')),
            ],
            options={
                'verbose_name': 'بدهی کمیسیون',
                'verbose_name_plural': 'بدهی\u200cهای کمیسیون',
                'ordering': ('is_settled', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت قبلی')),
                ('to_status', models.CharField(max_length=20, verbose_name='وضعیت جدید')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='city_drivers.servicerequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت سرویس',
                'verbose_name_plural': 'تاریخچه وضعیت سرویس\u200cها',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UrbanCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت داخلی شهری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_profiles_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urban_profile', to='customers.customer', verbose_name='مشتری')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_profiles_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
            ],
            options={
                'verbose_name': 'پروفایل مشتری شهری',
                'verbose_name_plural': 'پروفایل\u200cهای مشتریان شهری',
            },
        ),
        migrations.CreateModel(
            name='DriverAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(db_index=True, verbose_name='تاریخ (شمسی)')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('leave', 'مرخصی'), ('mission', 'ماموریت')], default='present', max_length=20, verbose_name='وضعیت حضور')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='ساعت ورود')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='ساعت خروج')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_attendances_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urban_attendances', to='drivers.driver', verbose_name='راننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_attendances_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
            ],
            options={
                'verbose_name': 'حضور و غیاب راننده',
                'verbose_name_plural': 'حضور و غیاب رانندگان',
                'ordering': ('-date', 'driver__name'),
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
