# Generated by Django 5.2.16 on 2026-09-02 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='مسدود شده')),
                ('block_reason', models.TextField(blank=True, null=True, verbose_name='دلیل مسدود شدن')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مسدود شدن')),
                ('unblocked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ رفع مسدودی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_drivers', to=settings.AUTH_USER_MODEL, verbose_name='مسدود شده توسط')),
                ('driver', models.OneToOneField(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_block', to=settings.AUTH_USER_MODEL, verbose_name='راننده')),
                ('unblocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unblocked_drivers', to=settings.AUTH_USER_MODEL, verbose_name='رفع مسدودی توسط')),
            ],
            options={
                'verbose_name': 'مسدودی راننده',
                'verbose_name_plural': 'مسدودی رانندگان',
            },
        ),
    ]
