# Generated by Django 5.2.16 on 2026-09-14 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد نقش')),
                ('name', models.CharField(max_length=60, verbose_name='نام نقش')),
                ('base_role', models.CharField(choices=[('admin', 'مدیر کل سیستم'), ('manager', 'مدیریت'), ('employee', 'کارمند'), ('driver', 'راننده'), ('customer', 'مشتری')], max_length=20, verbose_name='نقش پایه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نقش سفارشی',
                'verbose_name_plural': 'نقش\u200cهای سفارشی',
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='کلید ماژول')),
                ('name', models.CharField(max_length=100, verbose_name='نام ماژول')),
                ('url_prefix', models.CharField(max_length=100, verbose_name='پیشوند آدرس')),
                ('is_locked', models.BooleanField(default=False, verbose_name='قفل کامل (غیرقابل دسترسی برای همه بجز سوپر ادمین)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ماژول سیستم',
                'verbose_name_plural': 'ماژول\u200cهای سیستم',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='IssuanceQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('role', 'نقش'), ('user', 'کاربر')], max_length=10, verbose_name='دامنه')),
                ('role', models.CharField(blank=True, max_length=20, null=True, verbose_name='نقش')),
                ('period', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('total', 'کل عمر سیستم')], max_length=10, verbose_name='دوره')),
                ('max_count', models.PositiveIntegerField(verbose_name='حداکثر تعداد مجاز (0 = ممنوعیت کامل صدور)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotas_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuance_quotas', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سهمیه صدور بارنامه',
                'verbose_name_plural': 'سهمیه\u200cهای صدور بارنامه',
                'ordering': ('scope', 'period', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='عملیات')),
                ('target', models.CharField(blank=True, max_length=200, null=True, verbose_name='هدف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='عملگر')),
            ],
            options={
                'verbose_name': 'گزارش عملیات سیستم',
                'verbose_name_plural': 'گزارش\u200cهای عملیات سیستم',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SystemRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_module_locks', models.BooleanField(default=True, verbose_name='اعمال قفل ماژول\u200cها')),
                ('lock_all_modules', models.BooleanField(default=False, verbose_name='قفل کامل سیستم (فقط سوپر ادمین دسترسی دارد)')),
                ('enforce_quotas', models.BooleanField(default=True, verbose_name='اعمال سهمیه صدور بارنامه')),
                ('default_daily_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف پیش\u200cفرض روزانه صدور بارنامه (برای همه نقش\u200cها)')),
                ('wallet_enabled', models.BooleanField(default=True, verbose_name='فعال بودن کیف پول')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_rules_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخرین تغییر توسط')),
            ],
            options={
                'verbose_name': 'قانون سیستم',
                'verbose_name_plural': 'قوانین سیستم',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='نقش (کیف پول مشترک نقش)')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی (تومان)')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='مسدود (فریز)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', 'شارژ'), ('withdraw', 'برداشت'), ('adjust', 'اصلاحیه')], max_length=10, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (تومان)')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='موجودی پس از تراکنش')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='system_control.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ModuleAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='نقش')),
                ('is_locked', models.BooleanField(default=True, verbose_name='قفل')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rules', to='system_control.systemmodule', verbose_name='ماژول')),
            ],
            options={
                'verbose_name': 'قفل ماژول برای نقش',
                'verbose_name_plural': 'قفل ماژول\u200cها برای نقش\u200cها',
                'unique_together': {('module', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('allow', 'اجازه دسترسی'), ('deny', 'عدم دسترسی (قفل)')], max_length=10, verbose_name='وضعیت')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='system_control.systemmodule', verbose_name='ماژول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_overrides', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی اختصاصی کاربر به ماژول',
                'verbose_name_plural': 'دسترسی\u200cهای اختصاصی کاربران به ماژول\u200cها',
                'unique_together': {('module', 'user')},
            },
        ),
    ]
