# Generated by Django 5.2.16 on 2026-08-03 02:04

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captions', '0001_initial'),
        ('cargo', '0001_initial'),
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        ('issuance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijak',
            name='selected_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captions.caption'),
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='bijak',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_bijaks', to='cargo.cargo'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='bijak',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_bijaks', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bijaks', to='customers.customer'),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='bijak',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_bijaks', to='drivers.driver'),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='bijak',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_bijaks', to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='freight',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='کل کرایه'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='insurance',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ بیمه'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='issuance_datetime',
            field=django_jalali.db.models.jDateTimeField(db_index=True, verbose_name='تاریخ و ساعت صدور بارنامه'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='loading_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه بارگیری'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='scale_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه باسکول'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('sent', 'ارسال شده'), ('delivered', 'تحویل شده')], db_index=True, default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='total_fare',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='کرایه پرداختی در مقصد'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='tracking_code',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='type',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('Sent-Customer Version', 'ارسال شده-نسخه مشتری'), ('Sent-Driver Version', 'ارسال شده-نسخه راننده'), ('delivered', 'تحویل شده'), ('Delivered-Customer Version', 'تحویل شده-نسخه مشتری'), ('Delivered-Driver Version', 'تحویل شده-نسخه راننده'), ('canceled', 'لغو شده'), ('inactive', 'تکراری-غیر فعال')], db_index=True, default='sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='unloading_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه تخلیه'),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bijak',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='ارزش محموله'),
        ),
        migrations.CreateModel(
            name='BijakFinalStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(max_length=20, verbose_name='وضعیت جدید')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر وضعیت')),
                ('bijak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_status_logs', to='issuance.bijak', verbose_name='بارنامه')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت نهایی بارنامه',
                'verbose_name_plural': 'تاریخچه وضعیت نهایی بارنامه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Caption',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
