# Generated by Django 5.2.16 on 2026-08-03 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuance', '0002_alter_bijak_selected_caption_remove_cargo_created_by_and_more'),
        ('otp_verification', '0002_alter_otpcode_driver_alter_otplog_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
