# Generated by Django 5.2.16 on 2026-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuance', '0003_delete_driver_delete_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijak',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='توکن دسترسی عمومی'),
        ),
        migrations.AddField(
            model_name='bijak',
            name='can_edit_cargo',
            field=models.BooleanField(default=False, verbose_name='مجوز ویرایش محموله'),
        ),
        migrations.AddField(
            model_name='bijak',
            name='can_edit_driver',
            field=models.BooleanField(default=False, verbose_name='مجوز ویرایش راننده'),
        ),
        migrations.AddField(
            model_name='bijak',
            name='can_edit_financial',
            field=models.BooleanField(default=False, verbose_name='مجوز ویرایش بخش مالی'),
        ),
        migrations.AddField(
            model_name='bijak',
            name='can_edit_receiver',
            field=models.BooleanField(default=False, verbose_name='مجوز ویرایش گیرنده'),
        ),
        migrations.AddField(
            model_name='bijak',
            name='can_edit_sender',
            field=models.BooleanField(default=False, verbose_name='مجوز ویرایش فرستنده'),
        ),
    ]
