# Generated by Django 5.2.16 on 2026-08-10 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_approved', models.BooleanField(default=False, help_text='پس از ارائه اطلاعات تکمیلی به دفتر، از ادمین True شود.', verbose_name='تایید دفتر باربری')),
                ('registered_via_queue', models.BooleanField(default=True, verbose_name='ثبت\u200cنام از طریق صفحه نوبت\u200cدهی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_profile', to='drivers.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'پروفایل نوبت\u200cدهی راننده',
                'verbose_name_plural': 'پروفایل\u200cهای نوبت\u200cدهی',
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ صف')),
                ('number', models.PositiveIntegerField(verbose_name='شماره نوبت')),
                ('status', models.CharField(choices=[('waiting', 'در صف'), ('loaded', 'بار گرفته'), ('left', 'انصراف'), ('no_response', 'حذف (عدم پاسخ به اعلان)'), ('distance', 'حذف (خارج از محدوده دفتر)')], default='waiting', max_length=20, verbose_name='وضعیت')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پیوستن به صف')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='drivers.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'نوبت روزانه',
                'verbose_name_plural': 'نوبت\u200cهای روزانه',
                'ordering': ['date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='تاریخ')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال')),
                ('response', models.CharField(blank=True, choices=[('loaded', 'بار گرفته\u200cام'), ('waiting', 'هنوز در نوبت هستم')], max_length=10, null=True, verbose_name='پاسخ')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ')),
                ('sms_result', models.TextField(blank=True, verbose_name='نتیجه ارسال پیامک')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='driver_queue.queueticket', verbose_name='نوبت')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='queueticket',
            constraint=models.UniqueConstraint(fields=('driver', 'date'), name='uniq_ticket_per_driver_per_day'),
        ),
    ]
