# Generated by Django 5.2.16 on 2026-08-10 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_queue', '0001_initial'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueprofile',
            name='office_approved',
            field=models.BooleanField(default=False, help_text='پس از ارائه اطلاعات تکمیلی به دفتر، از پنل/ادمین True شود.', verbose_name='تایید دفتر باربری'),
        ),
        migrations.AlterField(
            model_name='queueticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'در صف'), ('loaded', 'بار گرفته'), ('left', 'انصراف'), ('no_response', 'حذف (عدم پاسخ به اعلان)'), ('distance', 'حذف (خارج از محدوده دفتر)'), ('staff', 'حذف توسط کاربر پنل')], default='waiting', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add_ticket', 'ثبت نوبت دستی'), ('remove_ticket', 'حذف نوبت'), ('mark_loaded', 'ثبت بارگیری'), ('approve_driver', 'تایید راننده'), ('unapprove_driver', 'لغو تایید راننده'), ('staff_add', 'افزودن کاربر مجاز'), ('staff_approve', 'تایید کاربر مجاز'), ('staff_unapprove', 'لغو تایید کاربر مجاز'), ('staff_remove', 'حذف کاربر مجاز')], max_length=20, verbose_name='عملیات')),
                ('detail', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drivers.driver', verbose_name='راننده')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='driver_queue.queueticket', verbose_name='نوبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش عملیات',
                'verbose_name_plural': 'گزارش عملیات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'کارمند'), ('manager', 'مدیریت')], default='staff', max_length=10, verbose_name='نقش')),
                ('approved', models.BooleanField(default=False, verbose_name='مورد تایید مدیر')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_staff', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر مجاز پنل',
                'verbose_name_plural': 'کاربران مجاز پنل',
            },
        ),
    ]
