# Generated by Django 5.2.16 on 2026-08-03 02:02

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد ملی')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('residence', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر سکونت')),
                ('certificate', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره گواهینامه')),
                ('certificate_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ صدور گواهینامه')),
                ('driver_smart_card', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='شماره هوشمند راننده')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='شماره تلفن راننده')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن دوم')),
                ('phone3', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن سوم')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver',
                'indexes': [models.Index(fields=['name'], name='driver_name_cf865e_idx'), models.Index(fields=['national_id'], name='driver_nationa_9dc15c_idx'), models.Index(fields=['certificate'], name='driver_certifi_31dad8_idx'), models.Index(fields=['phone'], name='driver_phone_69454b_idx')],
            },
        ),
    ]
