# Generated by Django 5.2.16 on 2026-08-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر کل سیستم'), ('manager', 'مدیریت'), ('employee', 'کارمند'), ('driver', 'راننده'), ('customer', 'مشتری')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر کل سیستم'), ('manager', 'مدیریت'), ('employee', 'کارمند'), ('driver', 'راننده'), ('customer', 'مشتری')], default='employee', max_length=20),
        ),
    ]
