# Generated by Django 5.2.16 on 2026-08-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_access_driver_queue',
            field=models.BooleanField(default=False, verbose_name='دسترسی به پنل نوبت\u200cدهی رانندگان'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_approve_queue_staff',
            field=models.BooleanField(default=False, verbose_name='دسترسی به تایید کارکنان نوبت\u200cدهی'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_otp_settings',
            field=models.BooleanField(default=False, verbose_name='دسترسی به تنظیمات OTP'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_queue_announcements',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مدیریت اعلان\u200cهای نوبت\u200cدهی'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_queue_settings',
            field=models.BooleanField(default=False, verbose_name='دسترسی به تنظیمات نوبت\u200cدهی'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_override_queue_rules',
            field=models.BooleanField(default=False, verbose_name='دسترسی به نادیده گرفتن قوانین نوبت\u200cدهی'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_send_sms_verification',
            field=models.BooleanField(default=False, verbose_name='دسترسی به ارسال پیامک تایید'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_verify_sms_code',
            field=models.BooleanField(default=False, verbose_name='دسترسی به تایید کد پیامکی'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_view_queue_reports',
            field=models.BooleanField(default=False, verbose_name='دسترسی به گزارش\u200cهای نوبت\u200cدهی'),
        ),
    ]
