# Generated by Django 5.2.16 on 2026-08-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rolepermission_can_access_driver_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='کد کاربر'),
        ),
    ]
