# Generated by Django 5.2.16 on 2026-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rolepermission_can_use_digital_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_access_dashboard',
            field=models.BooleanField(default=False, verbose_name='دسترسی به داشبورد رانندگان شهری'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_add_customers',
            field=models.BooleanField(default=False, verbose_name='ثبت و ویرایش مشتریان شهری'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_add_requests',
            field=models.BooleanField(default=False, verbose_name='ثبت درخواست سرویس شهری'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_assign_requests',
            field=models.BooleanField(default=False, verbose_name='تخصیص راننده به سرویس'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_edit_requests',
            field=models.BooleanField(default=False, verbose_name='ویرایش و تغییر وضعیت درخواست سرویس'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_manage_queue',
            field=models.BooleanField(default=False, verbose_name='مدیریت نوبت و حضور رانندگان'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_manage_rates',
            field=models.BooleanField(default=False, verbose_name='مدیریت نرخ\u200cنامه\u200cها'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_manage_settlements',
            field=models.BooleanField(default=False, verbose_name='تسویه بدهی کمیسیون رانندگان'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_view_customers',
            field=models.BooleanField(default=False, verbose_name='مشاهده مشتریان شهری'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_view_locations',
            field=models.BooleanField(default=False, verbose_name='مشاهده موقعیت رانندگان'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_view_queue',
            field=models.BooleanField(default=False, verbose_name='مشاهده نوبت و حضور رانندگان'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_view_rates',
            field=models.BooleanField(default=False, verbose_name='مشاهده نرخ\u200cنامه و محاسبه کرایه'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_view_reports',
            field=models.BooleanField(default=False, verbose_name='مشاهده گزارش\u200cهای روزانه مدیریت'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_urban_view_requests',
            field=models.BooleanField(default=False, verbose_name='مشاهده درخواست\u200cهای سرویس شهری'),
        ),
    ]
