# Generated by Django 5.2.17 on 2026-09-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rolepermission_can_urban_access_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_print_without_approval',
            field=models.BooleanField(default=False, verbose_name='اجازه چاپ بارنامه بدون نیاز به تایید مدیریت'),
        ),
    ]
