# Generated by Django 5.2.16 on 2026-08-03 02:02

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('vant pikan kof saf', 'وانت پیکان کف صاف'), ('vant pikan mamoli', 'وانت پیکان معمولی'), ('vant pikan tak', 'وانت پیکان تک'), ('vant pikan doganeh', 'وانت پیکان دوگانه'), ('vant pikan doganeh factory', 'وانت پیکان دوگانه کارخانه'), ('vant pikan doganeh handmade', 'وانت پیکان دوگانه دستی'), ('vant nisan kof saf', 'وانت نیسان کف صاف'), ('vant nisan mamoli', 'وانت نیسان معمولی'), ('vant nisan tak', 'وانت نیسان تک'), ('vant nisan dizel', 'وانت نیسان دیزل'), ('vant nisan doganeh', 'وانت نیسان دوگانه'), ('vant nisan doganeh factory', 'وانت نیسان دوگانه کارخانه'), ('vant nisan doganeh handmade', 'وانت نیسان دوگانه دستی'), ('vant nisan kof mobli', 'وانت نیسان کف مبلی'), ('vant nisan mosaqaf', 'وانت نیسان مسقف'), ('arisan', 'وانت آریسان'), ('arisan 2', 'وانت آریسان ۲'), ('mazda', 'وانت مزدا'), ('zamyad', 'وانت زامیاد'), ('Bari chobi 7T', 'باری چوبی-۳ تا ۷ تن'), ('Bari chobi 10T', 'باری چوبی-۷ تا ۱۰ تن'), ('Bari chobi 13T', 'باری چوبی-۱۰ تا ۱۳ تن'), ('Bari chobi 17T', 'باری چوبی-۱۳ تا ۱۷ تن'), ('Bari chobi 20T', 'باری چوبی-۱۷ تا ۲۰ تن'), ('Bari chobi +20T', 'باری چوبی بالای ۲۰ تن'), ('Bari mosaqaf 6W-7T', 'مسقف ۶ چرخ-۴ تا ۷ تن'), ('Bari mosaqaf 6W-10T', 'مسقف ۶ چرخ-۷ تا ۱۰ تن'), ('Bari mosaqaf 6W-13T', 'مسقف ۶ چرخ-۱۰ تا ۱۳ تن'), ('khavar mosaqaf 7T', 'مسقف خاور-۴ تا ۷ تن'), ('Bari mosavi 6W-13T', 'معمولی ۶ چرخ-۱۰ تا ۱۳ تن'), ('Bari kafi 6W-7T', 'کفی ۶ چرخ-۴ تا ۷ تن'), ('Bari kafi 6W-10T', 'کفی ۶ چرخ-۷ تا ۱۰ تن'), ('Bari kafi 6W-13T', 'کفی ۶ چرخ-۱۰ تا ۱۳ تن'), ('Bari kafi 6W-17T', 'کفی ۶ چرخ-۱۳ تا ۱۷ تن'), ('Bari kafi 6W-20T', 'کفی ۶ چرخ-۱۷ تا ۲۰ تن'), ('Bari kafi 6W-20T+', 'کفی ۶ چرخ-بالای ۲۰ تن'), ('Bari kafi 18W', 'کفی ۱۸ چرخ'), ('Bari flezi 7T', 'باری فلزی-۳ تا ۷ تن'), ('Bari flezi 10T', 'باری فلزی-۷ تا ۱۰ تن'), ('Bari flezi 13T', 'باری فلزی-۱۰ تا ۱۳ تن'), ('Bari flezi 17T', 'باری فلزی-۱۳ تا ۱۷ تن'), ('Bari flezi 20T', 'باری فلزی-۱۷ تا ۲۰ تن'), ('Bari flezi +20T', 'باری فلزی بالای ۲۰ تن'), ('Bari otaqdar 4w', 'اتاقدار ۴ چرخ'), ('Bari otaqdar 10w', 'اتاقدار ۱۰ چرخ'), ('Bari otaqdar 6w-7T', 'اتاقدار ۶ چرخ-۴ تا ۷ تن'), ('Bari otaqdar 6w-20T', 'اتاقدار ۶ چرخ-۱۷ تا ۲۰ تن'), ('Bari otaqdar 808', 'اتاقدار ۸۰۸'), ('Bari baqaldar chadari 12w', 'بغلدار چادری ۱۲ چرخ'), ('Bari baqaldar chadari khavar', 'بغلدار چادری خاور'), ('Bari baqaldar mamoli 12w', 'بغلدار معمولی ۱۲ چرخ'), ('Bari baqaldar mamoli 6w', 'بغلدار معمولی ۶ چرخ'), ('Bari baqaldar mamoli 18w', 'بغلدار معمولی ۱۸ چرخ'), ('Bari baqaldar mamoli 6w-7T', 'بغلدار معمولی ۶ چرخ-۴ تا ۷ تن'), ('Bari kompreci 6w', 'کمپرسی ۶ چرخ-۴ تا ۷ تن'), ('Tak baqal bazsho', 'تک بغل بازشو'), ('eisozo', 'ایسوزو'), ('608', 'خاور ۶۰۸'), ('808', 'خاور ۸۰۸'), ('kamunet van', 'کامیونت-ون'), ('kamunet force', 'کامیونت فورس'), ('kamunet', 'کامیونت بالای ۴ تن'), ('kamunet felezi', 'کامیونت-باری فلزی')], max_length=50, verbose_name='نوع ناوگان')),
                ('room_model', models.CharField(choices=[('Normal', 'معمولی'), ('flat_floor', 'کف صاف'), ('sofa_floor', 'کف مبلی')], default='Normal', max_length=50, verbose_name='مدل اتاق ناوگان')),
                ('Animal_feed_license', models.CharField(blank=True, choices=[('No', 'ندارد'), ('Yes', 'دارد')], default='No', max_length=6, null=True, verbose_name='مجوز حمل خوراک دام')),
                ('veterinary_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='کد دامپزشکی')),
                ('license_plate_two_digit', models.CharField(max_length=2, verbose_name='دو رقم پلاک')),
                ('license_plate_alphabet', models.CharField(max_length=1, verbose_name='الفبای پلاک')),
                ('license_plate_three_digit', models.CharField(max_length=3, verbose_name='سه رقم پلاک')),
                ('license_plate_series', models.CharField(max_length=2, verbose_name='سری پلاک')),
                ('vehicle_smart_card', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='هوشمند ناوگان')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بیمه نامه')),
                ('insurance_policy_expiry', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ اعتبار بیمه نامه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='انتخاب راننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ناوگان',
                'verbose_name_plural': 'ناوگان\u200cها',
                'db_table': 'vehicle',
                'indexes': [models.Index(fields=['driver'], name='vehicle_driver__4704df_idx'), models.Index(fields=['type'], name='vehicle_type_bd4e16_idx'), models.Index(fields=['vehicle_smart_card'], name='vehicle_vehicle_cb4d3e_idx')],
            },
        ),
    ]
