# Generated by Django 4.2.21 on 2026-02-24 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReleasedTrackingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="duplicate_audit.duplicatecluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DuplicateWaybillSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_waybill_id", models.IntegerField()),
                ("tracking_code", models.CharField(max_length=100)),
                ("issuer_name", models.CharField(max_length=255)),
                ("sender_name", models.CharField(max_length=255)),
                ("receiver_name", models.CharField(max_length=255)),
                ("driver_name", models.CharField(max_length=255)),
                ("cargo_name", models.CharField(max_length=255)),
                ("cargo_weight", models.FloatField()),
                (
                    "freight_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("cargo_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("loading_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "unloading_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("scale_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "final_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("sent", "ارسال شده"),
                            ("delivered", "تحویل شده"),
                            ("canceled", "لغو شده"),
                            ("inactive", "غیر فعال"),
                            ("customer_copy", "نسخه مشتری"),
                            ("inactive_duplicate", "تکراری-غیرفعال"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("customer_id", models.IntegerField(blank=True, null=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="duplicate_audit.duplicatecluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DuplicateApplyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_waybill_id", models.IntegerField()),
                ("old_status", models.CharField(max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                (
                    "old_tracking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "new_tracking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
