# Generated by Django 4.2.21 on 2026-02-25 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("duplicate_audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duplicatewaybillsnapshot",
            name="cargo_value",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="duplicatewaybillsnapshot",
            name="cargo_weight",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="duplicatewaybillsnapshot",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="duplicate_audit.duplicatecluster",
            ),
        ),
        migrations.AlterField(
            model_name="duplicatewaybillsnapshot",
            name="freight_amount",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="duplicatewaybillsnapshot",
            name="loading_cost",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="duplicatewaybillsnapshot",
            name="scale_cost",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="duplicatewaybillsnapshot",
            name="unloading_cost",
            field=models.CharField(max_length=15),
        ),
    ]
