# Generated by Django 5.2.16 on 2026-08-03 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='نام و نام خانوادگی فرستنده')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('postal', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone2', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
                'indexes': [models.Index(fields=['name'], name='customer_name_364ac9_idx'), models.Index(fields=['national_id'], name='customer_nationa_758745_idx'), models.Index(fields=['phone'], name='customer_phone_ea919e_idx')],
            },
        ),
    ]
