import os
import sys
from dotenv import load_dotenv

load_dotenv()
"""
Django settings for SadraBar project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-development-key-change-me-in-production'
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")
PUBLIC_DOMAIN = os.getenv("PUBLIC_DOMAIN", "http://localhost:8000")

CSRF_FAILURE_VIEW = 'issuance.views.error_views.csrf_failure'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'accounts',
    'dashboard',
    'homePage',
    'issuance',
    'captions',
    'cargo',
    'customers',
    'drivers',
    'fleet',
    # 'jalali_date',
    'report',
    # 'django_celery_beat',
    'duplicate_audit',
    'otp_verification',
    'printing',
    'driver_queue',
    'user_management',
    'system_control',
    'city_drivers',

]

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")

AUTH_USER_MODEL = 'accounts.User'
LOGIN_REDIRECT_URL = 'home'  # صفحه‌ای که بعد از لاگین می‌ره (پیش‌فرض)
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# defaults
JALALI_DATE_DEFAULTS = {
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',

        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'system_control.middleware.ModuleAccessMiddleware',
    'issuance.middleware.CurrentUserMiddleware',

]

ROOT_URLCONF = 'SadraBar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SadraBar.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        "NAME": os.path.join(BASE_DIR, os.getenv("DB_NAME", "db.sqlite3")),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True
USE_L10N = True
USE_TZ = False

# Static files (css, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'public_html', 'media')
PWA_CACHE_VERSION = os.getenv("PWA_CACHE_VERSION", "2026-09-28-1")

# ========== PWA آفلاین + همگام‌سازی صف درخواست‌ها ==========
# تگ Background Sync؛ درخواست‌های آفلاین با این تگ دوباره ارسال می‌شوند
PWA_SYNC_TAG = os.getenv("PWA_SYNC_TAG", "sadrabar-outbox-sync")
# حداکثر تلاش برای هر درخواست در صف؛ بعد از این تعداد از صف حذف می‌شود
PWA_SYNC_MAX_ATTEMPTS = int(os.getenv("PWA_SYNC_MAX_ATTEMPTS", "40"))
# فاصله بین ارسال هر آیتم صف (میلی‌ثانیه) تا سرور زیر فشار نرود
PWA_SYNC_RETRY_DELAY_MS = int(os.getenv("PWA_SYNC_RETRY_DELAY_MS", "700"))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_URL = os.getenv("SITE_URL", PUBLIC_DOMAIN)

# ========== تنظیمات SMS.ir ==========
SMS_IR_API_KEY = os.getenv("SMS_IR_API_KEY", "")
SMS_IR_PATTERN_CODE = os.getenv("SMS_IR_PATTERN_CODE", "")
SMS_IR_LINE_NUMBER = os.getenv("SMS_IR_LINE_NUMBER", "")

# برای محیط لوکال، ارسال واقعی را غیرفعال می‌کنیم
SMS_IR_FAKE_MODE = env_bool("SMS_IR_FAKE_MODE", default=True)

# تنظیمات لاگینگ

# ========== Email Settings ==========
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # برای توسعه: ایمیل‌ها در کنسول نمایش داده می‌شوند
# برای محیط تولید، از SMTP استفاده کنید:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@sadrabar.ir')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ========== Django REST Framework Settings ==========
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# ========== Rate Limiting Settings ==========
RATE_LIMIT_ENABLE = True
RATE_LIMIT_REQUESTS = 10  # requests per minute per IP/user

# ========== Security Headers ==========
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ---------------- ماژول نوبت‌دهی ----------------
# اگر app label اپ رانندگان شما "drivers" نیست، این مقدار را اصلاح کنید
QUEUE_DRIVER_MODEL = "drivers.Driver"

QUEUE_BASE_URL = "https://your-domain.com"  # دامنه لینک‌های پیامکی
QUEUE_SMS_GATEWAY = "driver_queue.sms.ConsoleSmsGateway"
# OFFICE_LOCATION = "35.6997,51.3380"  # مختصات مستقیم دفتر باربری
# OFFICE_LOCATION = "https://maps.google.com/?q=35.6997,51.3380"  # یا لینک گوگل مپ
OFFICE_LOCATION = "35.6997,51.3380"  # مختصات دفتر باربری (می‌تواند لینک هم باشد)
# اختیاری (با پیش‌فرض):
# QUEUE_START_TIME = "08:00"
# QUEUE_END_TIME = "11:00"
# QUEUE_ANNOUNCE_TIME = "11:00"
# QUEUE_ANNOUNCE_WINDOW_MINUTES = 30
# QUEUE_RESPONSE_GRACE_MINUTES = 15
# QUEUE_GEOFENCE_RADIUS_KM = 5.0
# QUEUE_WORKING_WEEKDAYS = (0, 1, 2, 3, 5, 6)  # شنبه تا پنج‌شنبه (جمعه=4 غیرفعال)
# QUEUE_HOLIDAYS = ["2026-08-14"]
