# Generated by Django 4.2.21 on 2026-05-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issuance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("code", models.CharField(blank=True, max_length=6, null=True)),
                ("status", models.CharField(default="INFO", max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="issuance.driver",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="issuance.bijak",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Log",
                "verbose_name_plural": "OTP Logs",
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issuance.driver",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="issuance.bijak"
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Code",
                "verbose_name_plural": "OTP Codes",
                "indexes": [
                    models.Index(
                        fields=["driver", "waybill"],
                        name="otp_verific_driver__75c15f_idx",
                    )
                ],
            },
        ),
    ]
