# Generated by Django 4.2.21 on 2026-05-11 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issuance", "0002_alter_caption_name_alter_customer_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaybillPrintOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="کد تأیید"
                    ),
                ),
                (
                    "print_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد دفعات چاپ"
                    ),
                ),
                (
                    "last_print_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان آخرین چاپ"
                    ),
                ),
                (
                    "otp_created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تولید کد"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="کد تأیید شده؟"),
                ),
                (
                    "bijak",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_otp",
                        to="issuance.bijak",
                        verbose_name="بارنامه",
                    ),
                ),
                (
                    "last_print_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخرین چاپ توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت چاپ بارنامه",
                "verbose_name_plural": "ثبت چاپ بارنامه\u200cها",
            },
        ),
    ]
