# Generated by Django 5.2.16 on 2026-08-03 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='نام محموله')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن/حجم')),
                ('weight_2', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='وزن/حجم دوم')),
                ('package_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='نوع بسته بندی')),
                ('number_of_packaging', models.IntegerField(blank=True, null=True, verbose_name='تعداد بسته بندی')),
                ('origin', models.CharField(db_index=True, max_length=50, verbose_name='مبدأ بارگیری')),
                ('destination', models.CharField(db_index=True, max_length=50, verbose_name='مقصد تخلیه')),
                ('created_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cargo',
                'indexes': [models.Index(fields=['name'], name='cargo_name_8d0b75_idx'), models.Index(fields=['origin'], name='cargo_origin_a5288b_idx'), models.Index(fields=['destination'], name='cargo_destina_e7e9b5_idx')],
            },
        ),
    ]
