# Generated by Django 5.2.16 on 2026-08-30 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شهر')),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام استان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='cargo',
            new_name='cargo_origin__ff871a_idx',
            old_name='cargo_origin_a5288b_idx',
        ),
        migrations.RenameIndex(
            model_name='cargo',
            new_name='cargo_destina_e3252a_idx',
            old_name='cargo_destina_e7e9b5_idx',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='وزن/حجم دوم'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_destinations', to='cargo.city', verbose_name='مقصد تخلیه'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_origins', to='cargo.city', verbose_name='مبدأ بارگیری'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cargo.province', verbose_name='استان'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'name')},
        ),
    ]
