# Generated by Django 5.2.16 on 2026-09-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_city_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.IntegerField(verbose_name='وزن/حجم'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight_2',
            field=models.IntegerField(default=0, verbose_name='وزن/حجم دوم'),
        ),
    ]
